import { WordItem } from "../interfaces/interfaces"
import { nanoid } from "nanoid"

export const WORDS:WordItem[] = [
    { name:"Medellín", id: nanoid(), category:"Lugar" },
    { name:"Milán", id: nanoid(), category:"Lugar" },
    { name:"Elche", id: nanoid(), category:"Lugar" },
    { name:"Venecia", id: nanoid(), category:"Lugar" },
    { name:"Roma", id: nanoid(), category:"Lugar" },
    { name:"Pueblito paisa", id: nanoid(), category:"Lugar" },
    { name:"Estatua de la libertad", id: nanoid(), category:"Lugar" },
    { name:"Santa Marta", id: nanoid(), category:"Lugar" },
    { name:"Machu Pichu", id: nanoid(), category:"Lugar" },
    { name:"Barcelona", id: nanoid(), category:"Lugar" },
    { name:"La Guajira", id: nanoid(), category:"Lugar" },
    { name:"Egipto", id: nanoid(), category:"Lugar" },
    { name:"Perro salchicha", id: nanoid(), category:"Animal" },
    { name:"Halcón", id: nanoid(), category:"Animal" },
    { name:"Pez payaso", id: nanoid(), category:"Animal" },
    { name:"Ornitorrinco", id: nanoid(), category:"Animal" },
    { name:"Sapoperro", id: nanoid(), category:"Animal" },
    { name:"Cucarrón pelotero", id: nanoid(), category:"Animal" },
    { name:"Leopardo", id: nanoid(), category:"Animal" },
    { name:"Tiranosaurio rex", id: nanoid(), category:"Animal" },
    { name:"Guepardo", id: nanoid(), category:"Animal" },
    { name:"Tortuga", id: nanoid(), category:"Animal" },
    { name:"Papagallo", id: nanoid(), category:"Animal" },
    { name:"Medusa", id: nanoid(), category:"Animal" },
    { name:"Águila", id: nanoid(), category:"Animal" },
    { name:"Sancocho", id: nanoid(), category:"Alimento" },
    { name:"Hígado encebollado", id: nanoid(), category:"Alimento" },
    { name:"Mondongo", id: nanoid(), category:"Alimento" },
    { name:"Sancocho", id: nanoid(), category:"Alimento" },
    { name:"Bandeja paisa", id: nanoid(), category:"Alimento" },
    { name:"Lasagna", id: nanoid(), category:"Alimento" },
    { name:"Butifarra", id: nanoid(), category:"Alimento" },
    { name:"Panzerotti", id: nanoid(), category:"Alimento" },
    { name:"Lengua", id: nanoid(), category:"Alimento" },
    { name:"Chunchurria", id: nanoid(), category:"Alimento" },
    { name:"Lumpia", id: nanoid(), category:"Alimento" },
    { name:"Arroz con pollo", id: nanoid(), category:"Alimento" },
    { name:"Spaghetti", id: nanoid(), category:"Alimento" },
    { name:"Fiambre", id: nanoid(), category:"Alimento" },
    { name:"Tajada de maduro", id: nanoid(), category:"Alimento" },
    { name:"Mazamorra", id: nanoid(), category:"Alimento" },
    { name:"Tamal", id: nanoid(), category:"Alimento" },
    { name:"Lámpara", id: nanoid(), category:"Cosa" },
    { name:"Sanitario", id: nanoid(), category:"Cosa" },
    { name:"Mojón", id: nanoid(), category:"Cosa" },
    { name:"Violín", id: nanoid(), category:"Cosa" },
    { name:"Calcetín", id: nanoid(), category:"Cosa" },
    { name:"Sombrero", id: nanoid(), category:"Cosa" },
    { name:"Silvato", id: nanoid(), category:"Cosa" },
    { name:"Gafas de natación", id: nanoid(), category:"Cosa" },
    { name:"Saxofón", id: nanoid(), category:"Cosa" },
    { name:"Audífonos", id: nanoid(), category:"Cosa" },
    { name:"Licuadora", id: nanoid(), category:"Cosa" },
    { name:"Sacapuntas", id: nanoid(), category:"Cosa" },
]

export const SHUFFLED_DEFAULT:WordItem[] = [
    { name:"-", id:nanoid(), category:"Alimento" },
    { name:"-", id:nanoid(), category:"Lugar" },
    { name:"-", id:nanoid(), category:"Cosa" },
]